### ISSUE TITLE
quill.scroll.descendant gives false hits on colour spans

### ISSUE THREAD

**Issue by unhammer** [quilljs/parchment#23]
I'm getting a weird error when trying to find a `descendant` of a certain blot-class on pasted-in content. If I have e.g.

```
  var contents = {"ops":[{"attributes":{"color":"#565657"},"insert":"abc "},
                         {"insert":"def "},
                         {"attributes":{"color":"#565657"},"insert":"xyz"}]};
  quill.setContents(contents);
```
and I have defined a class MyBlot extends Inline with tagName span, 
then quill.scroll.descendant claims the third insertion is an instanceof MyBlot. 

Full example at:

https://jsfiddle.net/fjg11pg6/1/

Also, if I have *actual* MyBlot's inside one of these colour spans, the answer from `descendant(MyBlot, …)` will be the text following the MyBlot.

**Comment by jhchen** [comment]
Since MyBlot uses `<span>` as the tag, it is effectively replacing the default InlineBlot, which is not necessarily a bad thing. But when Parchment needs a generic inline element for example to hold inline classes, styles or attributes, it will create a MyBlot now instead of an InlineBlot. So descendant() is indeed returning a bona fide MyBlot instance.

**Comment by unhammer** [comment]
Aha, I should've read https://quilljs.com/guides/cloning-medium-with-parchment/ more closely, now I see that I should specify `MyBlot.className="my"` instead of manually `node.setAttribute("class", "my");`. Thanks!
