### ISSUE TITLE
Unregister from registry

### ISSUE THREAD

**Issue by sionzee** [quilljs/parchment#70]
Hello. There is issue with global Quill.registry. 

When you are creating a two instances of Quill where every instance uses custom modules. Then they are shared because Quill#register is for global registering.

Would be great to have ability to register modules per instance or a way to unregister modules from Registry or from the specific instance.

There is simple workaround and it is to check the instance id in the constructor of custom module. If this instance has allowed this module and do stuffs with it. But it is an issue with overwriten modules. E.g.: I want use for one Quill custom keyboard and for second one the default keyboard.

I can do another workaround and that is calling super methods in overwriten methods. But it makes a mess in our code. 

I will prefer a method in Parchment what can unregister existing things. 

Thank you.

**Comment by jhchen** [comment]
Quill is moving towards supporting specifying the registry in the case of multiple Quill instances. So the solution would be instead of unregistering, to just have multiple registries and providing the one you want. Unregistering is also problematic as existing initialized editors do not expect this.
